# -*- coding: utf-8 -*-
"""유미팀_뉴스데이터_키워드추출.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y7WSG52Y3nWQGO-_PpPLtH7XYrZouYPl

## 작업위치 확인 및 변경
- 파일 불러오기 전 작업
"""

# Commented out IPython magic to ensure Python compatibility.
# 구글 드라이브 연결하기
from google.colab import drive
drive.mount('/content/drive')

# 현재 작업 위치 확인하기
import os
print(os.getcwd())

# 작업위치 변경하기
# %cd /content/drive/MyDrive/Colab Notebooks/실전프로젝트

# data 폴더 내에 json 파일 확인하기
import glob
json_files = glob.glob("data/*.json")
print("================================= 불러올 파일 확인 ====================================")
print("JSON 파일 개수:", len(json_files))
print(json_files)



"""## 전처리 방법 고민
- json 파일 불러와서 전처리 작업 진행
- ['data/raw_news_2023.json', 'data/raw_news_2024.json', 'data/raw_news_2025.json', 'data/raw_news_2026.json']

#### 파일 불러오기
- 내림차순 기준 20개 선택
"""

import json
import os
import pandas as pd

# 전처리에 사용 할 데이터 불러오기
# 불러올 JSON 파일 1개만 지정
file_path = "data/raw_news_2025.json"

# JSON 파일 불러오기
with open(file_path, "r", encoding="utf-8") as f:
    data = json.load(f)

print("파일 경로:", file_path)
print("데이터 타입:", type(data))

print("======================================================================")

# 데이터가 리스트 형태인 경우
if isinstance(data, list):
    print("전체 데이터 개수:", len(data))

    print("\n첫 번째 데이터 타입:", type(data[0]))
    print("\n첫 번째 데이터 내용:")
    print(json.dumps(data[0], ensure_ascii=False, indent=2))

    # 첫 번째 데이터가 딕셔너리라면 key 확인
    if isinstance(data[0], dict):
        print("\n첫 번째 데이터의 key 목록:")
        print(data[0].keys())
print("==============================  데이터 결측치 확인 ==========================")

# JSON 데이터를 DataFrame으로 변환
df = pd.DataFrame(data)

# 전체 데이터 크기 확인
print("데이터 크기:", df.shape)

# 컬럼별 결측치 개수 확인
print("\n컬럼별 결측치 개수:")
print(df.isnull().sum())

print("==============================  20개 샘플 데이터 복사본 생성 ==========================")

# 전체 df에서 앞의 20개 데이터만 선택하여 복사본 생성
# 원본 df는 그대로 유지하고, 이후 전처리 작업은 df_20으로 진행
df_20 = df.head(20).copy()

# 20개만 잘 가져왔는지 확인
print("원본 데이터 크기:", df.shape)
print("20개 샘플 데이터 크기:", df_20.shape)

# 20개 샘플 데이터 일부 확인
df_20.head()

df["category"].unique()



"""#### 파일 불러오기
- 카테고리 컬럼 선택해서 특정 값 지정해 랜덤으로 뽑기
"""

import json
import os
import pandas as pd

# 전처리에 사용 할 데이터 불러오기
# 불러올 JSON 파일 1개만 지정
file_path = "data/raw_news_2025.json"

# JSON 파일 불러오기
with open(file_path, "r", encoding="utf-8") as f:
    data = json.load(f)

print("파일 경로:", file_path)
print("데이터 타입:", type(data))

print("======================================================================")

# 데이터가 리스트 형태인 경우
if isinstance(data, list):
    print("전체 데이터 개수:", len(data))

    print("\n첫 번째 데이터 타입:", type(data[0]))
    print("\n첫 번째 데이터 내용:")
    print(json.dumps(data[0], ensure_ascii=False, indent=2))

    # 첫 번째 데이터가 딕셔너리라면 key 확인
    if isinstance(data[0], dict):
        print("\n첫 번째 데이터의 key 목록:")
        print(data[0].keys())

print("==============================  데이터 결측치 확인 ==========================")

# JSON 데이터를 DataFrame으로 변환
df = pd.DataFrame(data)

# 전체 데이터 크기 확인
print("데이터 크기:", df.shape)

# 컬럼별 결측치 개수 확인
print("\n컬럼별 결측치 개수:")
print(df.isnull().sum())

print("==============================  지정 카테고리별 랜덤 100개씩 총 400개 샘플 데이터 복사본 생성 ==========================")

# 선택할 category 값 목록
target_categories = ["소자본창업", "창업트렌드", "무인매장", "배달창업"]

# 지정한 category 값에 해당하는 데이터만 필터링
df_target = df[df["category"].isin(target_categories)].copy()

# 각 category 값마다 랜덤으로 100개씩 선택
df_400 = (
    df_target
    .groupby("category", group_keys=False)
    .apply(lambda x: x.sample(n=100, random_state=42))
    .copy()
)

# 기존 인덱스를 컬럼으로 유지
df_400 = df_400.reset_index(drop=False)

# 결과 확인
print("원본 데이터 크기:", df.shape)
print("선택한 카테고리 데이터 크기:", df_target.shape)
print("카테고리별 선택 데이터 개수:")
print(df_400["category"].value_counts())

print("최종 샘플 데이터 크기:", df_400.shape)

# 샘플 데이터 일부 확인
df_400.head()

df_400.columns



"""#### 뉴스 본문 텍스트 노이즈 제거 코드
- clean_content : 노이즈 제거된 문장 데이터 (BERTopic 입력용)
"""

import re
import pandas as pd


def clean_content(text):
    # content 값이 비어 있거나 NaN인 경우 빈 문자열로 처리
    if pd.isna(text):
        return ""

    # 숫자, NaN 등이 섞여 있을 가능성을 대비해 문자열로 변환
    text = str(text)

    # 이메일 주소 제거
    # 예: abc@gmail.com, reporter@news.co.kr
    text = re.sub(
        r"[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}",
        " ",
        text
    )

    # URL 제거
    # 예: http://example.com, https://news.com/article
    text = re.sub(
        r"http[s]?://\S+|www\.\S+",
        " ",
        text
    )

    # /텍스트 형태 제거
    # 예: /텍스트, /뉴스, /기사본문 등
    text = re.sub(
        r"/[가-힣A-Za-z0-9_]+",
        " ",
        text
    )

    # 실제 줄바꿈, 엔터, 탭 문자 제거
    # 예: \n, \r, \t
    text = re.sub(r"[\n\r\t]", " ", text)

    # 문자열 형태로 저장된 줄바꿈 문자 제거
    # 예: "\\n" 형태로 들어간 문자
    text = text.replace("\\n", " ")

    # 이스케이프된 따옴표 제거
    # 예: \'벤처·스타트업 근로시간 제도개편 간담회\'
    # 결과: 벤처·스타트업 근로시간 제도개편 간담회
    text = re.sub(r"\\['\"]", " ", text)

    # 본문에 남아 있는 \ 기호 제거
    # 예: \, \\, \\\ 등 연속된 \ 기호를 공백으로 변경
    text = re.sub(r"\\+", " ", text)

    # 일반 따옴표 제거
    # 예: '문장', "문장" 형태에서 따옴표만 제거
    text = re.sub(r"[\"']", " ", text)

    # <내용> 형태 제거
    # 예: <저작권자>, <사진>, <뉴스본문> 등 꺾쇠괄호와 내부 내용 전체 제거
    text = re.sub(r"<[^>]*>", " ", text)

    # 재판매 및 DB 금지 문구 제거
    # 예: *재판매 및 DB 금지, 재판매 및 DB 금지
    text = re.sub(
        r"\*?\s*재판매\s*및\s*DB\s*금지",
        " ",
        text,
        flags=re.IGNORECASE
    )

    # 대괄호로 묶인 출처/지역/언론사/광고 정보 제거
    # 예: [서울=뉴시스], [사진=대통령실 제공], [광고]
    # 대괄호와 그 안의 내용 전체를 제거함
    text = re.sub(r"\[[^\]]*\]", " ", text)

    # 소괄호로 묶인 사진 설명, 출처, 부가 설명 제거
    # 예: (사진=대통령실 제공), (대통령실통신사진기자단)
    # 소괄호와 그 안의 내용 전체를 제거함
    text = re.sub(r"\([^)]*\)", " ", text)

    # 기사 본문에 포함된 날짜 형식 제거
    # 예: 2023.01.31. / 2023.1.31
    text = re.sub(r"\d{4}\.\d{1,2}\.\d{1,2}\.?", " ", text)

    # 한글 이름 + 기자 표현 제거
    # 예: 홍길동 기자, 김철수기자
    text = re.sub(r"[가-힣]{2,4}\s*기자", " ", text)

    # 기자 = 형태 제거
    # 예: 기자=, 기자 =
    text = re.sub(r"기자\s*=", " ", text)

    # | ... 기자 | 형태 제거
    # 예: | 스마트에프엔 = 정민석 기자 |
    text = re.sub(
    r"\|[^|]*기자[^|]*\|",
    " ",
    text)

    # 저작권, 무단전재, 재배포 금지, 제보 문구 제거
    # 예: 무단 전재, 재배포 금지, Copyright, ⓒ, 제보를 기다립니다
    text = re.sub(
        r"(무단\s*전재|재배포\s*금지|ⓒ|Copyright|제보를 기다립니다)",
        " ",
        text,
        flags=re.IGNORECASE
    )

    # 불필요한 특수기호 제거
    # 예: ▲, ▶, *, =, … 기호 제거
    text = re.sub(r"[▲▶△■*=…]", " ", text)

    # 여러 개의 공백을 하나의 공백으로 정리
    # 앞뒤 공백은 strip()으로 제거
    text = re.sub(r"\s+", " ", text)

    return text.strip()


# content 컬럼의 원본 뉴스 본문을 전처리한 뒤 clean_content 컬럼에 저장
df_400["clean_content"] = df_400["content"].apply(clean_content)

# 전처리 전 content와 전처리 후 clean_content를 비교 확인
df_400[["content", "clean_content"]].head()

df_400.head()

df_400["clean_content"][150]



"""#### 노이즈 데이터 제거 후 불용어 사전 적용
- analysis_content: 명사추출 + 불용어 제거된 단어 데이터 (빈도 분석, 워드클라우드, 키워드 후보 확인용)
"""

!pip install kiwipiepy -q
from kiwipiepy import Kiwi
import pandas as pd

# 형태소 분석기 초기화
kiwi = Kiwi()


# ============================================================
# 불용어 사전
# ============================================================
# 분석에는 자주 등장하지만 의미가 약한 단어를 제거하기 위한 목록
# 프로젝트 결과를 확인하면서 계속 추가/수정하면 됨
# ============================================================

STOPWORDS = {
    # ============================================================
    # 1. 일반 불용어
    # ============================================================
    # 문장에 자주 등장하지만 키워드 분석 의미가 약한 단어
    "것", "수", "등", "및", "때", "중", "더", "또",
    "관련", "경우", "대상", "약",

    # ============================================================
    # 2. 조사·연결·전환 표현
    # ============================================================
    # 문장 연결에는 사용되지만 핵심 키워드로 보기 어려운 표현
    "위해", "통해", "대한", "또한", "한편",
    "따라", "이에", "다만", "특히",

    # ============================================================
    # 3. 시점 표현
    # ============================================================
    # 기사 작성 시점이나 시간 흐름을 나타내지만 트렌드 키워드로 보기 어려운 표현
    "이번", "지난", "올해", "내년", "최근", "현재", "향후",
    "오늘", "내일", "이날",

    # ============================================================
    # 4. 인물명 및 직책 관련 단어
    # ============================================================
    # 특정 인물명이나 직책명이 반복 등장하여
    # 창업 트렌드 키워드 분석에 불필요한 영향을 주는 경우 제거
    "윤석열", "모하메드", "황현기", "호나우지뉴",
    "대통령", "장관", "기자", "대표", "위원장",
    "의원", "총리", "회장", "사장", "교수",

    # ============================================================
    # 5. 지명 및 국가명
    # ============================================================
    # 특정 국가명·지역명이 반복적으로 등장하지만
    # 분석 목적상 핵심 키워드가 아닌 경우 제거
    "한국", "미국", "중국", "일본", "서울",
    "아랍에미리트", "부산", "인천", "경기",

    # ============================================================
    # 6. 기관명 및 기업명
    # ============================================================
    # 특정 기관명이나 기업명이 반복 등장하여
    # 전체 토픽/키워드 결과를 왜곡하는 경우 제거
    "중소벤처기업부", "중기부", "한국무역협회",
    "대한상공회의소", "벤처기업협회", "고용노동부",
    "두산에너빌리티",

    # ============================================================
    # 7. 언론사 및 뉴스 출처 관련 단어
    # ============================================================
    # 기사 출처나 언론사명으로, 트렌드 분석 키워드와 직접 관련이 낮은 단어
    "한국경제", "이투데이", "머니투데이", "News1",
    "뉴시스", "연합뉴스", "조선일보",

    # ============================================================
    # 8. 뉴스 기사 형식 관련 단어
    # ============================================================
    # 뉴스 본문 구조상 반복적으로 등장하는 표현
    "뉴스", "보도", "사진", "제공", "자료", "출처",
    "취재", "인터뷰", "관계자", "업계",

    # ============================================================
    # 9. 기사 서술 표현
    # ============================================================
    # 기사 문체에서 자주 등장하지만 핵심 키워드로 보기 어려운 표현
    "밝혔다", "말했다", "설명했다", "전했다", "덧붙였다",
    "설명", "강조", "진행", "개최", "발표", "참석",
    "예정", "참여",

    # ============================================================
    # 10. 분석 결과에서 의미가 약한 단어
    # ============================================================
    # 실제 키워드 추출 결과를 확인하며 추가한 프로젝트 맞춤형 불용어
    "광범위", "천문학"
}


# ============================================================
# 명사 추출 + 불용어 제거 함수
# ============================================================
# clean_content 컬럼의 문장 데이터에서 명사 중심 단어만 추출하고,
# 불용어 사전에 포함된 단어를 제거하여 분석용 텍스트를 생성한다.
# ============================================================

def remove_stopwords_and_extract_nouns(text):
    # 값이 비어 있거나 NaN인 경우 빈 문자열 반환
    if pd.isna(text):
        return ""

    text = str(text)

    words = []

    # Kiwi 형태소 분석 수행
    for token in kiwi.tokenize(text):
        word = token.form
        pos = token.tag

        # NNG: 일반명사
        # NNP: 고유명사
        # VV: 동사
        # VA: 형용사
        if pos in ["NNG", "NNP", "VV", "VA"]:

            # 한 글자 단어 제거
            if len(word) <= 1:
                continue

            # 불용어 제거
            if word in STOPWORDS:
                continue

            words.append(word)

    return " ".join(words)


# clean_content 컬럼을 기준으로 명사 추출 및 불용어 제거
df_400["analysis_content"] = df_400["clean_content"].apply(remove_stopwords_and_extract_nouns)

# 결과 확인
df_400[["content", "clean_content", "analysis_content"]].head()



"""#### KeyBERT 작업 수행
- analysis_content 컬럼 사용
"""

!pip install keybert sentence-transformers -q

from keybert import KeyBERT
from sentence_transformers import SentenceTransformer
import pandas as pd

# ============================================================
# KeyBERT 키워드 추출
# ============================================================
# 사용 컬럼:
# - analysis_content
#   → 노이즈 제거 + 명사 추출 + 불용어 제거가 완료된 분석용 텍스트
#
# 결과 컬럼:
# - keybert_keywords
#   → 기사별 추출 키워드 목록
# - keybert_keyword_scores
#   → 기사별 키워드와 점수 정보
# ============================================================


# 한국어 문장 임베딩 모델 로드
embedding_model = SentenceTransformer("jhgan/ko-sroberta-multitask")

# KeyBERT 모델 초기화
kw_model = KeyBERT(model=embedding_model)


def extract_keybert_keywords(text):
    # 값이 비어 있거나 NaN인 경우 빈 리스트 반환
    if pd.isna(text):
        return []

    text = str(text).strip()

    # 전처리 결과가 비어 있는 경우 빈 리스트 반환
    if text == "":
        return []

    # KeyBERT 키워드 추출
    keywords = kw_model.extract_keywords(
        text,
        keyphrase_ngram_range=(1, 1),  # 1단어 키워드 추출
        stop_words=None,               # 불용어는 이미 analysis_content에서 제거했으므로 None
        top_n=20,                      # 기사 1개당 상위 20개 키워드 추출
        use_mmr=True,                  # 비슷한 키워드 반복 감소
        diversity=0.5                  # 키워드 다양성 조절
    )

    return keywords


# analysis_content 컬럼을 기준으로 KeyBERT 키워드 추출
df_400["keybert_keyword_scores"] = df_400["analysis_content"].apply(extract_keybert_keywords)

# 키워드만 따로 리스트 형태로 저장
df_400["keybert_keywords"] = df_400["keybert_keyword_scores"].apply(
    lambda keywords: [keyword for keyword, score in keywords]
)

# 결과 확인
df_400[["content", "clean_content", "analysis_content", "keybert_keywords", "keybert_keyword_scores"]].head()

df_400["keybert_keywords"][120]

df_400["url"].iloc[120]



"""#### BERTopic 작업 수행
- clean_content 컬럼 사용
"""

!pip install bertopic -q

from bertopic import BERTopic
from sklearn.feature_extraction.text import CountVectorizer
from sentence_transformers import SentenceTransformer
from umap import UMAP
from hdbscan import HDBSCAN
import pandas as pd
import torch


# ============================================================
# BERTopic 토픽 모델링
# ============================================================
# 사용 데이터프레임:
# - df_400
#
# 사용 컬럼:
# - clean_content
#   → 노이즈 제거는 완료되었지만 문장 형태가 유지된 뉴스 본문
#
# 목적:
# - 뉴스 본문을 의미적으로 비슷한 토픽끼리 묶는다.
# - 토픽별 대표 키워드를 추출한다.
# ============================================================


# ============================================================
# 1. BERTopic 토픽 키워드 추출용 토크나이저
# ============================================================
# clean_content 문장은 그대로 BERTopic에 입력하되,
# 토픽 대표 단어를 뽑을 때는 Kiwi 형태소 분석 + 불용어 제거를 적용한다.
# 이 코드에서는 일반명사(NNG)만 토픽 키워드 후보로 사용한다.
# ============================================================

def kiwi_tokenizer(text):
    tokens = []

    for token in kiwi.tokenize(text):
        word = token.form
        pos = token.tag

        # NNG: 일반명사
        # NNP: 고유명사
        # VV : 동사
        # VA : 형용사
        if pos in ["NNG", "NNP", "VV", "VA"]:

            # 한 글자 단어 제거
            if len(word) <= 1:
                continue

            # 불용어 제거
            if word in STOPWORDS:
                continue

            tokens.append(word)

    return tokens


# ============================================================
# 2. BERTopic 입력 데이터 준비
# ============================================================
# df_400의 clean_content 컬럼에서 비어 있지 않은 문장만 사용
# ============================================================

df_bertopic = df_400[df_400["clean_content"].notna()].copy()
df_bertopic = df_bertopic[df_bertopic["clean_content"].str.strip() != ""].copy()

docs = df_bertopic["clean_content"].tolist()

print("BERTopic에 입력할 문서 개수:", len(docs))


# ============================================================
# 3. CountVectorizer 설정
# ============================================================
# 토픽별 대표 키워드를 뽑을 때 사용할 토큰화 방식 지정
# ============================================================

vectorizer_model = CountVectorizer(
    tokenizer=kiwi_tokenizer,
    token_pattern=None,
    ngram_range=(1, 1),
    min_df=1,
    max_df=0.9
)


# ============================================================
# 4. 임베딩 모델 설정
# ============================================================
# 한국어 문장 임베딩 모델 사용
# - snunlp/KR-SBERT-V40K-klueNLI-augSTS
# ============================================================

device = "cuda" if torch.cuda.is_available() else "cpu"

embedding_model = SentenceTransformer(
    "snunlp/KR-SBERT-V40K-klueNLI-augSTS",
    device=device
)

print("사용 device:", device)


# ============================================================
# 5. UMAP / HDBSCAN 설정
# ============================================================
# df_400은 400개 샘플 데이터이므로,
# 기존 df_20보다 조금 더 안정적인 클러스터링 설정을 사용한다.
# ============================================================

umap_model = UMAP(
    n_neighbors=15,
    n_components=5,
    min_dist=0.0,
    metric="cosine",
    random_state=42
)

hdbscan_model = HDBSCAN(
    min_cluster_size=10,
    min_samples=3,
    metric="euclidean",
    prediction_data=True
)


# ============================================================
# 6. BERTopic 모델 생성 및 학습
# ============================================================

topic_model = BERTopic(
    embedding_model=embedding_model,
    vectorizer_model=vectorizer_model,
    umap_model=umap_model,
    hdbscan_model=hdbscan_model,
    language="multilingual",
    calculate_probabilities=True,
    verbose=True
)

topics, probs = topic_model.fit_transform(docs)


# ============================================================
# 7. df_400에 BERTopic 결과 저장
# ============================================================
# topic 번호를 원본 df_400의 해당 행에 다시 저장
# ============================================================

df_bertopic["bertopic_topic"] = topics

# df_400에 bertopic_topic 컬럼 생성
df_400["bertopic_topic"] = None

# clean_content가 존재했던 행에만 topic 결과 저장
df_400.loc[df_bertopic.index, "bertopic_topic"] = df_bertopic["bertopic_topic"]


# ============================================================
# 8. 토픽 정보 확인
# ============================================================

topic_info = topic_model.get_topic_info()

print("생성된 토픽 정보:")
display(topic_info)

# df_400 결과 확인
df_400[["clean_content", "bertopic_topic"]].head()

df_400[
    [
        "clean_content",
        "analysis_content",
        "keybert_keywords",
        "bertopic_topic"
    ]
].head()

topic_info = topic_model.get_topic_info()
topic_info

