# -*- coding: utf-8 -*-
"""재한팀_DBR,HBR_키워드추출.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1awPU_rI3GI5wrT02rcbkAb9OpWD7VA_A

# 작업위치 확인 및 변경
- 파일 불러오기 전 작업
"""

# Commented out IPython magic to ensure Python compatibility.
# 구글 드라이브 연결하기
from google.colab import drive
drive.mount('/content/drive')

# 현재 작업 위치 확인하기
import os
print(os.getcwd())

# 작업위치 변경하기
# %cd /content/drive/MyDrive/Colab Notebooks/실전프로젝트

# data 폴더 내에 csv 파일 확인하기
import glob

csv_files = glob.glob("data/*.csv")

print("================================= 불러올 파일 확인 ====================================")
print("CSV 파일 개수:", len(csv_files))
print(csv_files[:5])



"""## 재한팀 DBR,HBR 데이터 확인"""

import pandas as pd

# 첫 번째 CSV 파일 불러오기
df_hbr = pd.read_csv(csv_files[0])

# 데이터 크기 확인
print("데이터 크기:", df_hbr.shape)

# 컬럼 확인
print("컬럼 목록:")
print(df_hbr.columns)

# 상위 5개 행 확인
df_hbr.tail()

df_hbr['content'][2]



"""#### df_hbr 데이터 결측치제거, 데이터범위 맞추기 (2023~2026년)"""

# published_date 결측치 제거 후 복사본 생성
df_hbr_copy = df_hbr.dropna(subset=["published_date"]).copy()

# published_date 컬럼을 문자열로 변환하고 앞뒤 공백 제거
df_hbr_copy["published_date"] = df_hbr_copy["published_date"].astype(str).str.strip()

# 2023, 2024, 2025, 2026으로 시작하는 날짜만 필터링
df_hbr_date = df_hbr_copy[
    df_hbr_copy["published_date"].str.startswith(("2023.", "2024.", "2025.", "2026."))
].copy()

# 결과 확인
print("원본 데이터 개수:", len(df_hbr))
print("published_date 결측치 제거 후 데이터 개수:", len(df_hbr_copy))
print("2023~2026 데이터 개수:", len(df_hbr_date))

# 필터링된 날짜 컬럼 일부 확인
df_hbr_date["published_date"].head()

df_hbr_date





"""## 노이즈 데이터 제거"""

import re
import pandas as pd


def clean_content(text):
    # content 값이 비어 있거나 NaN인 경우 빈 문자열로 처리
    if pd.isna(text):
        return ""

    # 숫자, NaN 등이 섞여 있을 가능성을 대비해 문자열로 변환
    text = str(text)

    # 원문 | 이후의 푸터 영역 전체 제거
    # 예: 원문 | https://hbr.org/... 이후 URL, 저자소개, 에디팅 정보 제거
    text = re.sub(
        r"(?m)^\s*원문\s*\|[\s\S]*$",
        " ",
        text
    )

    # 이메일 주소 제거
    # 예: abc@gmail.com, reporter@news.co.kr
    text = re.sub(
        r"[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}",
        " ",
        text
    )

    # URL 제거
    # 예: http://example.com, https://news.com/article
    text = re.sub(
        r"http[s]?://\S+|www\.\S+",
        " ",
        text
    )

    # 실제 줄바꿈, 엔터, 탭 문자 제거
    # 예: \n최근 설문조사\n → 최근 설문조사
    text = re.sub(r"[\n\r\t]", " ", text)

    # 문자열 형태로 저장된 줄바꿈 문자 제거
    # 예: "\\n최근 설문조사\\n" → 최근 설문조사
    text = text.replace("\\n", " ")

    # 이스케이프된 따옴표 제거
    # 예: \'벤처·스타트업 근로시간 제도개편 간담회\'
    # 결과: 벤처·스타트업 근로시간 제도개편 간담회
    text = re.sub(r"\\['\"]", " ", text)

    # 본문에 남아 있는 \ 기호 제거
    # 예: \, \\, \\\ 등 연속된 \ 기호를 공백으로 변경
    text = re.sub(r"\\+", " ", text)

    # 일반 따옴표 제거는 제외
    # 기존 코드:
    # text = re.sub(r"[\"']", " ", text)

    # <내용> 형태 제거
    # 예: <저작권자>, <사진>, <뉴스본문> 등 꺾쇠괄호와 내부 내용 전체 제거
    text = re.sub(r"<[^>]*>", " ", text)

    # 재판매 및 DB 금지 문구 제거
    text = re.sub(
        r"\*?\s*재판매\s*및\s*DB\s*금지",
        " ",
        text,
        flags=re.IGNORECASE
    )

    # 대괄호로 묶인 출처/지역/언론사/광고 정보 제거
    text = re.sub(r"\[[^\]]*\]", " ", text)

    # 소괄호로 묶인 사진 설명, 출처, 부가 설명 제거
    text = re.sub(r"\([^)]*\)", " ", text)

    # 기사 본문에 포함된 날짜 형식 제거
    # 예: 2023.01.31. / 2023.1.31
    text = re.sub(r"\d{4}\.\d{1,2}\.\d{1,2}\.?", " ", text)

    # 한글 이름 + 기자 표현 제거
    # 예: 홍길동 기자, 김철수기자
    text = re.sub(r"[가-힣]{2,4}\s*기자", " ", text)

    # 기자 = 형태 제거
    # 예: 기자=, 기자 =
    text = re.sub(r"기자\s*=", " ", text)

    # 저작권, 무단전재, 재배포 금지, 제보 문구 제거
    text = re.sub(
        r"(무단\s*전재|재배포\s*금지|ⓒ|Copyright|제보를 기다립니다)",
        " ",
        text,
        flags=re.IGNORECASE
    )

    # 불필요한 특수기호 제거
    # 예: ▲, ▶, *, =, … 기호 제거
    text = re.sub(r"[▲▶*=…]", " ", text)

    # 여러 개의 공백을 하나의 공백으로 정리
    text = re.sub(r"\s+", " ", text)

    return text.strip()


# content 컬럼을 전처리한 뒤 clean_content 컬럼에 저장
df_hbr_date["clean_content"] = df_hbr_date["content"].apply(clean_content)

# 전처리 전 content와 전처리 후 clean_content 비교 확인
df_hbr_date[["content", "clean_content"]].head()

df_hbr_date['clean_content'][0]



"""## 불용어 사전 적용"""

!pip install kiwipiepy
from kiwipiepy import Kiwi
import pandas as pd

# 형태소 분석기 초기화
kiwi = Kiwi()


# ============================================================
# HBR / DBR 아티클용 불용어 사전
# ============================================================
# 뉴스 기사용 불용어에서 언론사/기자/보도 표현은 줄이고,
# 아티클 구조상 자주 반복되는 표현을 추가한 버전
# ============================================================

STOPWORDS = {
    # ============================================================
    # 1. 일반 불용어
    # ============================================================
    "것", "수", "등", "및", "때", "중", "더", "또",
    "관련", "경우", "대상", "약", "정도", "부분",
    "내용", "방식", "방법", "수준", "결과", "사례",

    # ============================================================
    # 2. 조사·연결·전환 표현
    # ============================================================
    "위해", "통해", "대한", "또한", "한편",
    "따라", "이에", "다만", "특히", "반면",
    "예를", "그러나", "하지만", "그리고", "따라서",
    "즉", "먼저", "마지막", "다음",

    # ============================================================
    # 3. 시점 표현
    # ============================================================
    "이번", "지난", "올해", "내년", "최근", "현재", "향후",
    "오늘", "내일", "이날", "이후", "이전", "초기",
    "단기", "장기", "매년",

    # ============================================================
    # 4. 아티클 구조 관련 표현
    # ============================================================
    "아티클", "필자", "저자", "본문", "원문",
    "에디팅", "설문조사", "설문", "조사", "연구",
    "인터뷰", "응답자", "대상자", "질문", "답변",
    "응답", "비율", "퍼센트",

    # ============================================================
    # 5. 순서·단계 서술 표현
    # ============================================================
    "첫번째", "두번째", "세번째", "네번째", "다섯번째",
    "여섯번째", "일곱번째",
    "단계", "요소", "구성", "항목", "모델",

    # ============================================================
    # 6. 인물명 및 직책 관련 단어
    # ============================================================
    # 단, CFO, CIO, CTO 같은 직책 약어는 AI 투자 분석에서 의미가 있을 수 있어 유지
    "토머스", "대븐포트", "락스", "스리니바산",
    "김민수", "교수", "학과장", "방문", "연구원",
    "고문", "창립자", "공동", "최고운영책임자",

    # ============================================================
    # 7. 기관명·기업명
    # ============================================================
    # 기업명 자체가 키워드맵 목적에 불필요하면 제거
    "밥슨", "칼리지", "Babson", "College",
    "Metropoulos", "Institute", "Technology",
    "Entrepreneurship", "MIT", "Deloitte",
    "Return", "Institute", "Opera", "Solutions",
    "Scaled", "Agile", "Capital", "One",
    "Merck", "KGaA", "Schneider", "Electric",
    "Olympus", "Corporation", "Americas",
    "Ally", "Financial", "CarMax", "DBS",

    # ============================================================
    # 8. 아티클 서술 표현
    # ============================================================
    "말했다", "설명했다", "밝혔다", "전했다", "강조했다",
    "보고했다", "답했다", "응답했다", "꼽았다",
    "제시했다", "확인했다", "살펴봤다",
    "설명", "강조", "제시", "확인", "발견",
    "포함", "달성", "추구", "활용", "도입",
    "운영", "수행", "공개", "공유",

    # ============================================================
    # 9. 의미가 너무 넓은 추상어
    # ============================================================
    # 분석 결과에서 너무 많이 나오면 추가 제거 가능
    "기업", "조직", "리더", "경영진", "직원",
    "사용자", "고객", "업무", "경제", "재무"
}


# ============================================================
# 명사 추출 + 불용어 제거 함수
# ============================================================

def remove_stopwords_and_extract_nouns(text):
    # 값이 비어 있거나 NaN인 경우 빈 문자열 반환
    if pd.isna(text):
        return ""

    text = str(text)

    words = []

    # Kiwi 형태소 분석 수행
    for token in kiwi.tokenize(text):
        word = token.form
        pos = token.tag

        # NNG: 일반명사
        # SL: 영어/외국어 표현, 예: AI, ROI, CFO
        if pos in ["NNG", "SL"]:

            # 한 글자 단어 제거
            if len(word) <= 1:
                continue

            # 불용어 제거
            if word in STOPWORDS:
                continue

            words.append(word)

    return " ".join(words)


# clean_content 컬럼을 기준으로 명사 추출 및 불용어 제거
df_hbr_date["analysis_content"] = df_hbr_date["clean_content"].apply(
    remove_stopwords_and_extract_nouns
)

# 결과 확인
df_hbr_date[["content", "clean_content", "analysis_content"]].head()

df_hbr_date["analysis_content"][20]



"""## KeyBERT + BERTopic 사용

- 노이즈 데이터 제거, 불용어 사전 적용된 각각의 컬럼이 생성된 df_hbr_date 데이터프레임에 대해서<br> 전체 데이터를 사용하지 않고, 랜덤하게 20개 추출해 복사본을 만들어서 KeyBERT + BERTopic 수행
"""

# df_hbr_date에서 랜덤하게 20개 행 추출 후 복사본 생성
df_20 = df_hbr_date.sample(n=20, random_state=42).copy()

# 인덱스 정리
df_20 = df_20.reset_index(drop=True)

# 결과 확인
print("df_hbr_date 전체 데이터 개수:", len(df_hbr_date))
print("df_20 데이터 개수:", len(df_20))

df_20.head()



"""## KeyBERT 키워드 추출

### 사용 데이터프레임
- `df_20`

### 사용 컬럼
- `analysis_content`

`analysis_content` 컬럼은 노이즈 제거, 명사 추출, 불용어 제거가 완료된 분석용 텍스트이다.

### 추출 조건
- Kiwi 형태소 분석 결과 중 `NNG` 일반명사만 사용한다.
- 한 글자 단어는 제거한다.
- 불용어 사전에 포함된 단어는 제거한다.
- KeyBERT 입력 텍스트는 `NNG`만 남긴 텍스트를 사용한다.

### 추출 방식
- KeyBERT를 사용하여 문서별 핵심 키워드를 추출한다.
- 키워드는 1개 단어로 구성된 단어만 추출한다.
- 문서 1개당 상위 10개의 키워드를 추출한다.

### 결과 컬럼
- `keybert_keyword_scores`  
  - 키워드와 유사도 점수 정보를 함께 저장한다.

- `keybert_keywords`  
  - 키워드만 리스트 형태로 저장한다.

### 주의사항
- `NNG` 일반명사만 사용하면 `AI`, `ROI`, `CFO`와 같은 영어 약어는 제외될 수 있다.
- 영어 약어까지 키워드로 사용하려면 `NNG`와 함께 `SL` 품사를 포함해야 한다.
"""

!pip install keybert sentence-transformers kiwipiepy

from keybert import KeyBERT
from kiwipiepy import Kiwi
import pandas as pd


# 형태소 분석기 초기화
kiwi = Kiwi()

# KeyBERT 모델 초기화
kw_model = KeyBERT(model="paraphrase-multilingual-MiniLM-L12-v2")


def extract_nng_text(text):
    """
    입력 텍스트에서 NNG(일반명사)만 추출하여
    KeyBERT 입력용 문자열로 변환하는 함수
    """
    if pd.isna(text):
        return ""

    text = str(text).strip()

    if text == "":
        return ""

    words = []

    for token in kiwi.tokenize(text):
        word = token.form
        pos = token.tag

        # NNG: 일반명사만 사용
        if pos == "NNG":

            # 한 글자 단어 제거
            if len(word) <= 1:
                continue

            # 불용어 제거
            if word in STOPWORDS:
                continue

            words.append(word)

    return " ".join(words)


def extract_keybert_keywords(text):
    # 값이 비어 있거나 NaN인 경우 빈 리스트 반환
    if pd.isna(text):
        return []

    # NNG 일반명사만 남긴 텍스트 생성
    nng_text = extract_nng_text(text)

    # NNG 추출 결과가 비어 있으면 빈 리스트 반환
    if nng_text == "":
        return []

    # KeyBERT 키워드 추출
    keywords = kw_model.extract_keywords(
        nng_text,
        keyphrase_ngram_range=(1, 1),  # 1개 단어 키워드만 추출
        stop_words=None,               # 불용어는 위에서 직접 제거했으므로 None
        top_n=10                       # 문서 1개당 상위 10개 키워드 추출
    )

    return keywords


# analysis_content 컬럼을 기준으로 KeyBERT 키워드 추출
df_20["keybert_keyword_scores"] = df_20["analysis_content"].apply(
    extract_keybert_keywords
)

# 키워드만 따로 리스트 형태로 저장
df_20["keybert_keywords"] = df_20["keybert_keyword_scores"].apply(
    lambda keywords: [keyword for keyword, score in keywords]
)

# 결과 확인
df_20[
    [
        "content",
        "clean_content",
        "analysis_content",
        "keybert_keywords",
        "keybert_keyword_scores"
    ]
].head()

# df_20의 0번째 행에 있는 keybert_keyword_scores 컬럼 값 확인
df_20.loc[, "keybert_keyword_scores"]



"""## BERTopic 토픽 모델링

### 사용 데이터프레임
- `df_20`

### 사용 컬럼
- `clean_content`

`clean_content` 컬럼은 노이즈 제거는 완료되었지만, 문장 형태가 유지된 본문 데이터이다.

### 토픽 키워드 추출 조건
- Kiwi 형태소 분석 결과 중 `NNG` 일반명사만 사용한다.
- 토픽을 설명하는 키워드는 1개 단어로 구성된 단어만 사용한다.
- 불용어 사전에 포함된 단어는 제거한다.

### 목적
- 본문 데이터를 의미적으로 비슷한 토픽끼리 묶는다.
- 각 토픽을 대표하는 주요 키워드를 추출한다.

### 주의사항
- 현재 사용하는 `df_20`은 20개 샘플 데이터이다.
- 따라서 전체 데이터를 사용했을 때보다 토픽 분류 품질이 낮을 수 있다.
- 현재 단계에서는 BERTopic 코드가 정상적으로 작동하는지 확인하는 테스트 용도로 사용한다.
"""

!pip install bertopic
from bertopic import BERTopic
from sklearn.feature_extraction.text import CountVectorizer
from sentence_transformers import SentenceTransformer
from umap import UMAP
from hdbscan import HDBSCAN
import pandas as pd

# ============================================================
# 1. BERTopic 토픽 키워드 추출용 토크나이저
# ============================================================
# clean_content 문장은 BERTopic 임베딩 입력으로 그대로 사용한다.
# 단, 토픽 대표 키워드를 뽑을 때는 Kiwi 형태소 분석을 적용한다.
# 여기서는 NNG(일반명사)만 토픽 키워드 후보로 사용한다.
# ============================================================

def kiwi_tokenizer(text):
    tokens = []

    if pd.isna(text):
        return tokens

    text = str(text)

    for token in kiwi.tokenize(text):
        word = token.form
        pos = token.tag

        # NNG: 일반명사만 사용
        if pos == "NNG":

            # 한 글자 단어 제거
            if len(word) <= 1:
                continue

            # 불용어 제거
            if word in STOPWORDS:
                continue

            tokens.append(word)

    return tokens


# ============================================================
# 2. BERTopic 입력 데이터 준비
# ============================================================
# df_20의 clean_content 컬럼에서 비어 있지 않은 문장만 사용
# ============================================================

df_bertopic = df_20[df_20["clean_content"].notna()].copy()
df_bertopic = df_bertopic[
    df_bertopic["clean_content"].astype(str).str.strip() != ""
].copy()

docs = df_bertopic["clean_content"].tolist()

print("BERTopic에 입력할 문서 개수:", len(docs))


# ============================================================
# 3. CountVectorizer 설정
# ============================================================
# 토픽별 대표 키워드를 뽑을 때 사용할 토큰화 방식 지정
# ngram_range=(1, 1)이므로 1개 단어 키워드만 생성
# ============================================================

vectorizer_model = CountVectorizer(
    tokenizer=kiwi_tokenizer,
    token_pattern=None,
    ngram_range=(1, 1),
    min_df=1,
    max_df=0.9
)


# ============================================================
# 4. 임베딩 모델 설정
# ============================================================
# clean_content 문장의 의미를 벡터로 변환하기 위한 다국어 임베딩 모델 사용
# ============================================================

embedding_model = SentenceTransformer("paraphrase-multilingual-MiniLM-L12-v2")


# ============================================================
# 5. UMAP / HDBSCAN 설정
# ============================================================
# df_20은 샘플 데이터 20개만 사용하므로,
# 작은 데이터에서도 토픽이 생성될 수 있도록 값을 낮게 설정
# ============================================================

umap_model = UMAP(
    n_neighbors=5,
    n_components=2,
    min_dist=0.0,
    metric="cosine",
    random_state=42
)

hdbscan_model = HDBSCAN(
    min_cluster_size=2,
    min_samples=1,
    metric="euclidean",
    prediction_data=True
)


# ============================================================
# 6. BERTopic 모델 생성 및 학습
# ============================================================

topic_model = BERTopic(
    embedding_model=embedding_model,
    vectorizer_model=vectorizer_model,
    umap_model=umap_model,
    hdbscan_model=hdbscan_model,
    language="multilingual",
    calculate_probabilities=True,
    verbose=True
)

topics, probs = topic_model.fit_transform(docs)


# ============================================================
# 7. df_20에 BERTopic 결과 저장
# ============================================================
# topic 번호를 원본 df_20의 해당 행에 다시 저장
# ============================================================

df_bertopic["bertopic_topic"] = topics

# df_20에 bertopic_topic 컬럼 생성
df_20["bertopic_topic"] = None

# clean_content가 존재했던 행에만 topic 결과 저장
df_20.loc[df_bertopic.index, "bertopic_topic"] = df_bertopic["bertopic_topic"]


# ============================================================
# 8. 토픽 정보 확인
# ============================================================

topic_info = topic_model.get_topic_info()

print("생성된 토픽 정보:")
display(topic_info)

# df_20 결과 확인
df_20[["clean_content", "bertopic_topic"]].head()



"""## DBR 데이터에도 동일하게 적용"""

import pandas as pd

# CSV 파일 불러오기
df_dbr = pd.read_csv(csv_files[1])

# 데이터 크기 확인
print("데이터 크기:", df_dbr.shape)

# 컬럼 확인
print("컬럼 목록:")
print(df_dbr.columns)

# 마지막 5개 행 확인
df_dbr.head()

print(df_dbr.isna().sum())
print(df_dbr.dtypes)



print("=" * 60)
print("[2단계] df_dbr 데이터 범위 맞추기")
print("=" * 60)

# published_date 컬럼을 문자열로 변환하고 앞뒤 공백 제거
df_dbr["published_date"] = df_dbr["published_date"].astype(str).str.strip()

# 2023년, 2024년, 2025년, 2026년이 포함된 행만 필터링 후 복사본 생성
df_dbr_date = df_dbr[
    df_dbr["published_date"].str.contains(
        "2023년|2024년|2025년|2026년",
        regex=True,
        na=False
    )
].copy()

print("-" * 60)
print("[결과 확인]")
print("-" * 60)

# 결과 확인
print("원본 데이터 개수:", len(df_dbr))
print("2023~2026 데이터 개수:", len(df_dbr_date))

df_dbr_date.head()



import re
import pandas as pd

print("=" * 60)
print("[3단계] DBR 본문 데이터 노이즈 제거")
print("=" * 60)


def clean_content(text):
    # content 값이 비어 있거나 NaN인 경우 빈 문자열로 처리
    if pd.isna(text):
        return ""

    # 숫자, NaN 등이 섞여 있을 가능성을 대비해 문자열로 변환
    text = str(text)

    # 원문 | 이후의 푸터 영역 전체 제거
    # 예: 원문 | https://... 이후 URL, 저자소개, 에디팅 정보 제거
    text = re.sub(
        r"(?m)^\s*원문\s*\|[\s\S]*$",
        " ",
        text
    )

    # 이메일 주소 제거
    text = re.sub(
        r"[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}",
        " ",
        text
    )

    # URL 제거
    text = re.sub(
        r"http[s]?://\S+|www\.\S+",
        " ",
        text
    )

    # 실제 줄바꿈, 엔터, 탭 문자 제거
    text = re.sub(r"[\n\r\t]", " ", text)

    # 문자열 형태로 저장된 줄바꿈 문자 제거
    text = text.replace("\\n", " ")

    # 이스케이프된 따옴표 제거
    text = re.sub(r"\\['\"]", " ", text)

    # 본문에 남아 있는 \ 기호 제거
    text = re.sub(r"\\+", " ", text)

    # <내용> 형태 제거
    text = re.sub(r"<[^>]*>", " ", text)

    # 재판매 및 DB 금지 문구 제거
    text = re.sub(
        r"\*?\s*재판매\s*및\s*DB\s*금지",
        " ",
        text,
        flags=re.IGNORECASE
    )

    # 대괄호로 묶인 출처/지역/언론사/광고 정보 제거
    text = re.sub(r"\[[^\]]*\]", " ", text)

    # 소괄호로 묶인 사진 설명, 출처, 부가 설명 제거
    text = re.sub(r"\([^)]*\)", " ", text)

    # 기사 본문에 포함된 날짜 형식 제거
    text = re.sub(r"\d{4}\.\d{1,2}\.\d{1,2}\.?", " ", text)

    # 한글 이름 + 기자 표현 제거
    text = re.sub(r"[가-힣]{2,4}\s*기자", " ", text)

    # 기자 = 형태 제거
    text = re.sub(r"기자\s*=", " ", text)

    # 저작권, 무단전재, 재배포 금지, 제보 문구 제거
    text = re.sub(
        r"(무단\s*전재|재배포\s*금지|ⓒ|Copyright|제보를 기다립니다)",
        " ",
        text,
        flags=re.IGNORECASE
    )

    # 불필요한 특수기호 제거
    text = re.sub(r"[▲▶*=…]", " ", text)

    # 여러 개의 공백을 하나의 공백으로 정리
    text = re.sub(r"\s+", " ", text)

    return text.strip()


# content 컬럼을 전처리한 뒤 clean_content 컬럼에 저장
df_dbr_date["clean_content"] = df_dbr_date["content"].apply(clean_content)

print("-" * 60)
print("[전처리 결과 확인]")
print("-" * 60)

# 전처리 전 content와 전처리 후 clean_content 비교 확인
df_dbr_date[["content", "clean_content"]].tail()



!pip install kiwipiepy

from kiwipiepy import Kiwi
import pandas as pd

print("=" * 60)
print("[4단계] df_dbr_date 명사 추출 및 불용어 제거")
print("=" * 60)

# 형태소 분석기 초기화
kiwi = Kiwi()


# ============================================================
# HBR / DBR 아티클용 불용어 사전
# ============================================================
# 뉴스 기사용 불용어에서 언론사/기자/보도 표현은 줄이고,
# 아티클 구조상 자주 반복되는 표현을 추가한 버전
# ============================================================

STOPWORDS = {
    # ============================================================
    # 1. 일반 불용어
    # ============================================================
    "것", "수", "등", "및", "때", "중", "더", "또",
    "관련", "경우", "대상", "약", "정도", "부분",
    "내용", "방식", "방법", "수준", "결과", "사례",

    # ============================================================
    # 2. 조사·연결·전환 표현
    # ============================================================
    "위해", "통해", "대한", "또한", "한편",
    "따라", "이에", "다만", "특히", "반면",
    "예를", "그러나", "하지만", "그리고", "따라서",
    "즉", "먼저", "마지막", "다음",

    # ============================================================
    # 3. 시점 표현
    # ============================================================
    "이번", "지난", "올해", "내년", "최근", "현재", "향후",
    "오늘", "내일", "이날", "이후", "이전", "초기",
    "단기", "장기", "매년",

    # ============================================================
    # 4. 아티클 구조 관련 표현
    # ============================================================
    "아티클", "필자", "저자", "본문", "원문",
    "에디팅", "설문조사", "설문", "조사", "연구",
    "인터뷰", "응답자", "대상자", "질문", "답변",
    "응답", "비율", "퍼센트",

    # ============================================================
    # 5. 순서·단계 서술 표현
    # ============================================================
    "첫번째", "두번째", "세번째", "네번째", "다섯번째",
    "여섯번째", "일곱번째",
    "단계", "요소", "구성", "항목", "모델",

    # ============================================================
    # 6. 인물명 및 직책 관련 단어
    # ============================================================
    "토머스", "대븐포트", "락스", "스리니바산",
    "김민수", "교수", "학과장", "방문", "연구원",
    "고문", "창립자", "공동", "최고운영책임자",

    # ============================================================
    # 7. 기관명·기업명
    # ============================================================
    "밥슨", "칼리지", "Babson", "College",
    "Metropoulos", "Institute", "Technology",
    "Entrepreneurship", "MIT", "Deloitte",
    "Return", "Institute", "Opera", "Solutions",
    "Scaled", "Agile", "Capital", "One",
    "Merck", "KGaA", "Schneider", "Electric",
    "Olympus", "Corporation", "Americas",
    "Ally", "Financial", "CarMax", "DBS",

    # ============================================================
    # 8. 아티클 서술 표현
    # ============================================================
    "말했다", "설명했다", "밝혔다", "전했다", "강조했다",
    "보고했다", "답했다", "응답했다", "꼽았다",
    "제시했다", "확인했다", "살펴봤다",
    "설명", "강조", "제시", "확인", "발견",
    "포함", "달성", "추구", "활용", "도입",
    "운영", "수행", "공개", "공유",

    # ============================================================
    # 9. 의미가 너무 넓은 추상어
    # ============================================================
    "기업", "조직", "리더", "경영진", "직원",
    "사용자", "고객", "업무", "경제", "재무"
}


# ============================================================
# 명사 추출 + 불용어 제거 함수
# ============================================================

def remove_stopwords_and_extract_nouns(text):
    # 값이 비어 있거나 NaN인 경우 빈 문자열 반환
    if pd.isna(text):
        return ""

    text = str(text)

    words = []

    # Kiwi 형태소 분석 수행
    for token in kiwi.tokenize(text):
        word = token.form
        pos = token.tag

        # NNG: 일반명사
        # SL: 영어/외국어 표현, 예: AI, ROI, CFO
        if pos in ["NNG", "SL"]:

            # 한 글자 단어 제거
            if len(word) <= 1:
                continue

            # 불용어 제거
            if word in STOPWORDS:
                continue

            words.append(word)

    return " ".join(words)


# clean_content 컬럼을 기준으로 명사 추출 및 불용어 제거
df_dbr_date["analysis_content"] = df_dbr_date["clean_content"].apply(
    remove_stopwords_and_extract_nouns
)

print("-" * 60)
print("[결과 확인]")
print("-" * 60)

# 결과 확인
df_dbr_date[["content", "clean_content", "analysis_content"]].head()

df_dbr_date["analysis_content"][0]



# df_dbr_date에서 상위 20개 행만 선택해서 복사본 생성
df_dbr_20 = df_dbr_date.head(20).copy()

# 결과 확인
print("df_dbr_date 데이터 개수:", len(df_dbr_date))
print("df_dbr_20 데이터 개수:", len(df_dbr_20))

df_dbr_20



!pip install keybert sentence-transformers -q

from keybert import KeyBERT
import pandas as pd

print("=" * 60)
print("[5단계] KeyBERT 키워드 추출")
print("=" * 60)


# ============================================================
# KeyBERT 키워드 추출
# ============================================================
# 사용 데이터프레임:
# - df_dbr_20
#
# 사용 컬럼:
# - analysis_content
#   → 노이즈 제거 + 명사 추출 + 불용어 제거가 완료된 분석용 텍스트
#
# 결과 컬럼:
# - keybert_keywords
#   → 기사별 추출 키워드 목록
#
# - keybert_keyword_scores
#   → 기사별 키워드와 유사도 점수 정보
# ============================================================


# KeyBERT 모델 초기화
# 한국어 텍스트에도 사용할 수 있는 다국어 문장 임베딩 모델 사용
kw_model = KeyBERT(model="paraphrase-multilingual-MiniLM-L12-v2")


def extract_keybert_keywords(text):
    # 값이 비어 있거나 NaN인 경우 빈 리스트 반환
    if pd.isna(text):
        return []

    text = str(text).strip()

    # 전처리 결과가 비어 있는 경우 빈 리스트 반환
    if text == "":
        return []

    # KeyBERT 키워드 추출
    keywords = kw_model.extract_keywords(
        text,
        keyphrase_ngram_range=(1, 1),  # 1개 단어로 구성된 키워드만 추출
        stop_words=None,               # 불용어는 이미 analysis_content에서 제거했으므로 None
        top_n=10                       # 기사 1개당 상위 10개 키워드 추출
    )

    return keywords


# analysis_content 컬럼을 기준으로 KeyBERT 키워드 추출
df_dbr_20["keybert_keyword_scores"] = df_dbr_20["analysis_content"].apply(
    extract_keybert_keywords
)

# 키워드만 따로 리스트 형태로 저장
df_dbr_20["keybert_keywords"] = df_dbr_20["keybert_keyword_scores"].apply(
    lambda keywords: [keyword for keyword, score in keywords]
)

print("-" * 60)
print("[KeyBERT 키워드 추출 결과 확인]")
print("-" * 60)

# 결과 확인
df_dbr_20[
    [
        "content",
        "clean_content",
        "analysis_content",
        "keybert_keywords",
        "keybert_keyword_scores"
    ]
].head()

