# -*- coding: utf-8 -*-
"""지원금공고확인.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fTH9Z0YPdtepIfDC0dBlfy4YP2aGAwqV

## 전체 수집용 코드
- 모집 진행여부가 Y인 공고 전체 수집
- totalCount 기준으로 전체 페이지 반복 호출
- 오늘 날짜 기준으로 접수 가능한 공고만 필터링
- 주요 컬럼만 표로 출력
"""

import requests
import pandas as pd
from getpass import getpass
from datetime import datetime
from zoneinfo import ZoneInfo
from math import ceil

# ============================================================
# 1. 인증키 입력
# ============================================================
SERVICE_KEY = getpass("공공데이터포털 인증키를 입력하세요: ")

# ============================================================
# 2. 지원사업 공고 정보 API URL
# ============================================================
url = "https://apis.data.go.kr/B552735/kisedKstartupService01/getAnnouncementInformation01"

# ============================================================
# 3. API 한 페이지 호출 함수
# ============================================================
def fetch_page(page, per_page=100):
    params = {
        "ServiceKey": SERVICE_KEY,
        "page": page,
        "perPage": per_page,
        "returnType": "json",
        "rcrt_prgs_yn": "Y"   # 모집진행여부 Y
    }

    response = requests.get(url, params=params, timeout=30)

    print(f"{page}페이지 상태코드:", response.status_code)

    # 응답이 정상 JSON인지 확인
    try:
        data = response.json()
    except Exception:
        print("JSON 변환 실패")
        print(response.text[:1000])
        raise

    return data

# ============================================================
# 4. 첫 페이지 호출
# ============================================================
per_page = 100
first_data = fetch_page(page=1, per_page=per_page)

print("응답 key:", first_data.keys())
print("현재 페이지 데이터 수:", first_data.get("currentCount"))
print("전체 데이터 수:", first_data.get("totalCount"))

# ============================================================
# 5. 전체 페이지 수 계산
# ============================================================
total_count = first_data.get("totalCount", 0)
total_pages = ceil(total_count / per_page)

print("전체 페이지 수:", total_pages)

# ============================================================
# 6. 전체 페이지 반복 수집
# ============================================================
all_items = first_data.get("data", [])

for page in range(2, total_pages + 1):
    page_data = fetch_page(page=page, per_page=per_page)
    all_items.extend(page_data.get("data", []))

# ============================================================
# 7. DataFrame 변환
# ============================================================
df = pd.DataFrame(all_items)

print("전체 수집 공고 수:", len(df))
display(df.head())

# ============================================================
# 8. 오늘 날짜 기준 모집 가능한 공고 필터링
# ============================================================
today = pd.Timestamp(datetime.now(ZoneInfo("Asia/Seoul")).date())

print("오늘 날짜:", today.date())

# 날짜 컬럼 변환
df["pbanc_rcpt_bgng_dt"] = pd.to_datetime(df["pbanc_rcpt_bgng_dt"], errors="coerce")
df["pbanc_rcpt_end_dt"] = pd.to_datetime(df["pbanc_rcpt_end_dt"], errors="coerce")

# 모집진행여부 정리
df["rcrt_prgs_yn"] = df["rcrt_prgs_yn"].astype(str).str.upper()

# 오늘 기준 접수 가능한 공고만 필터링
df_open_today = df[
    (df["rcrt_prgs_yn"] == "Y") &
    (df["pbanc_rcpt_bgng_dt"] <= today) &
    (df["pbanc_rcpt_end_dt"] >= today)
].copy()

print("오늘 기준 지원 모집 가능한 공고 수:", len(df_open_today))

# ============================================================
# 9. 주요 컬럼만 확인
# ============================================================
selected_cols = [
    "biz_pbanc_nm",          # 지원사업 공고명
    "pbanc_ctnt",            # 공고 내용
    "supt_biz_clsfc",        # 지원 분야
    "pbanc_rcpt_bgng_dt",    # 접수 시작일
    "pbanc_rcpt_end_dt",     # 접수 종료일
    "aply_trgt",             # 신청 대상
    "aply_trgt_ctnt",        # 신청 대상 내용
    "biz_enyy",              # 창업 기간
    "biz_trgt_age",          # 대상 연령
    "supt_regin",            # 지역명
    "prfn_matr",             # 우대 사항
    "rcrt_prgs_yn",          # 모집진행여부
    "detl_pg_url"            # 상세페이지 URL
]

existing_cols = [col for col in selected_cols if col in df_open_today.columns]

df_open_today_view = df_open_today[existing_cols]

display(df_open_today_view)

print("전체 수집 공고 수:", len(df))
print("오늘 기준 지원 모집 가능한 공고 수:", len(df_open_today))



from datetime import datetime
from zoneinfo import ZoneInfo
import pandas as pd

# 오늘 날짜: 한국 시간 기준
today = pd.Timestamp(datetime.now(ZoneInfo("Asia/Seoul")).date())

# 원본 df 복사
df_check = df.copy()

# 날짜 컬럼 변환
df_check["pbanc_rcpt_bgng_dt"] = pd.to_datetime(df_check["pbanc_rcpt_bgng_dt"], errors="coerce")
df_check["pbanc_rcpt_end_dt"] = pd.to_datetime(df_check["pbanc_rcpt_end_dt"], errors="coerce")

# 모집진행여부 정리
df_check["rcrt_prgs_yn"] = df_check["rcrt_prgs_yn"].astype(str).str.upper()

# 오늘 기준 모집 가능 여부 판단
df_check["오늘기준_모집가능"] = (
    (df_check["rcrt_prgs_yn"] == "Y") &
    (df_check["pbanc_rcpt_bgng_dt"] <= today) &
    (df_check["pbanc_rcpt_end_dt"] >= today)
)

# 오늘 기준 모집 가능한 공고만 추출
df_open_today = df_check[df_check["오늘기준_모집가능"] == True].copy()

print("오늘 날짜:", today.date())
print("오늘 기준 모집 가능한 공고 수:", len(df_open_today))

# 주요 컬럼만 확인
view_cols = [
    "biz_pbanc_nm",
    "pbanc_rcpt_bgng_dt",
    "pbanc_rcpt_end_dt",
    "rcrt_prgs_yn",
    "오늘기준_모집가능",
    "detl_pg_url"
]

display(df_open_today[view_cols].sort_values("pbanc_rcpt_bgng_dt"))



# 접수 시작일이 2026년인 공고만 선택
df_2026_start = df_open_today[
    df_open_today["pbanc_rcpt_bgng_dt"].dt.year == 2026
].copy()

print("접수 시작일이 2026년인 모집 가능 공고 수:", len(df_2026_start))

view_cols = [
    "biz_pbanc_nm",
    "pbanc_rcpt_bgng_dt",
    "pbanc_rcpt_end_dt",
    "rcrt_prgs_yn",
    "detl_pg_url"
]

display(df_2026_start[view_cols].sort_values("pbanc_rcpt_bgng_dt"))



# 접수 시작일이 2026년보다 이전인 공고만 선택
df_before_2026_start = df_open_today[
    df_open_today["pbanc_rcpt_bgng_dt"].dt.year < 2026
].copy()

print("접수 시작일이 2026년보다 이전인 모집 가능 공고 수:", len(df_before_2026_start))

view_cols = [
    "biz_pbanc_nm",
    "pbanc_rcpt_bgng_dt",
    "pbanc_rcpt_end_dt",
    "rcrt_prgs_yn",
    "detl_pg_url"
]

display(df_before_2026_start[view_cols].sort_values("pbanc_rcpt_bgng_dt"))



# ============================================================
# detl_pg_url 컬럼만 리스트로 추출하기
# 목적: 각 공고의 상세페이지 URL 내용을 직접 확인하기 위함
# ============================================================

# detl_pg_url 컬럼에서 결측값 제거 후 리스트로 변환
url_list = df_before_2026_start["detl_pg_url"].dropna().tolist()

print("URL 개수:", len(url_list))
print("상세페이지 URL 목록")

# 리스트 안의 URL을 번호와 함께 출력
for i, url in enumerate(url_list, start=1):
    print(f"{i}. {url}")



# ============================================================
# 접수 시작일이 2026년인 공고의 사업공고명 리스트 확인
# 목적:
# - 현재 모집중인 공고 중 접수 시작일이 2026년인 공고만 선택
# - biz_pbanc_nm 컬럼의 공고명을 리스트로 확인
# - 창업 지원과 관련된 공고인지 아닌지 공고명 기준으로 1차 검토
# ============================================================

import pandas as pd

# 원본 복사
df_2026_check = df_open_today.copy()

# 접수 시작일 컬럼을 datetime으로 변환
df_2026_check["pbanc_rcpt_bgng_dt"] = pd.to_datetime(
    df_2026_check["pbanc_rcpt_bgng_dt"],
    errors="coerce"
)

# 접수 시작일이 2026년인 공고만 선택
df_2026_start = df_2026_check[
    df_2026_check["pbanc_rcpt_bgng_dt"].dt.year == 2026
].copy()

# 접수 시작일 기준 정렬
df_2026_start = df_2026_start.sort_values("pbanc_rcpt_bgng_dt")

# biz_pbanc_nm 컬럼 값만 리스트로 변환
biz_pbanc_nm_list = (
    df_2026_start["biz_pbanc_nm"]
    .dropna()
    .astype(str)
    .tolist()
)

print("접수 시작일이 2026년인 모집중 공고 수:", len(df_2026_start))
print("공고명 리스트 개수:", len(biz_pbanc_nm_list))
print("=" * 80)

# 리스트 안에 들어있는 공고명 번호와 함께 출력
for i, name in enumerate(biz_pbanc_nm_list, start=1):
    print(f"{i}. {name}")

